// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/**
 * @title IVerifier
 * @notice Interface for ZK proof verifiers
 * @dev Implementations are typically generated by circom/snarkjs
 */
interface IVerifier {
    /**
     * @notice Verify a ZK-SNARK proof
     * @param proof The proof data (typically 8 uint256 values for Groth16)
     * @param publicInputs The public inputs to the circuit
     * @return valid True if the proof is valid
     */
    function verifyProof(
        uint256[8] calldata proof,
        uint256[4] calldata publicInputs
    ) external view returns (bool valid);
}

/**
 * @title IWithdrawVerifier
 * @notice Verifier for withdrawal proofs
 *
 * Public inputs:
 * [0] - Merkle root
 * [1] - Nullifier hash
 * [2] - Amount
 * [3] - Recipient address (as uint256)
 *
 * Private inputs (in the proof):
 * - Secret (random value known only to depositor)
 * - Path elements (Merkle proof)
 * - Path indices
 */
interface IWithdrawVerifier is IVerifier {
    // Inherits verifyProof from IVerifier
}

/**
 * @title IDepositVerifier
 * @notice Verifier for deposit commitment proofs
 *
 * Public inputs:
 * [0] - Commitment hash
 * [1] - Amount (encrypted)
 *
 * Private inputs:
 * - Secret
 * - Nullifier preimage
 * - Amount (plaintext)
 */
interface IDepositVerifier is IVerifier {
    // Inherits verifyProof from IVerifier
}
