#ifndef WATTX_FCMP_FFI_H
#define WATTX_FCMP_FFI_H

/* This file is auto-generated by cbindgen. Do not edit manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Success
 */
#define FCMP_SUCCESS 0

/**
 * Invalid parameter (null pointer, wrong size, etc.)
 */
#define FCMP_ERROR_INVALID_PARAM -1

/**
 * Proof generation failed
 */
#define FCMP_ERROR_PROOF_GENERATION -2

/**
 * Proof verification failed
 */
#define FCMP_ERROR_PROOF_VERIFICATION -3

/**
 * Memory allocation failed
 */
#define FCMP_ERROR_MEMORY -4

/**
 * Invalid point on curve
 */
#define FCMP_ERROR_INVALID_POINT -5

/**
 * Invalid scalar
 */
#define FCMP_ERROR_INVALID_SCALAR -6

/**
 * Not initialized
 */
#define FCMP_ERROR_NOT_INITIALIZED -7

/**
 * Internal error
 */
#define FCMP_ERROR_INTERNAL -99

/**
 * Size of a scalar in bytes
 */
#define SCALAR_SIZE 32

/**
 * Size of a point in bytes (compressed)
 */
#define POINT_SIZE 32

/**
 * Size of an output tuple (O, I, C = 3 points)
 */
#define OUTPUT_TUPLE_SIZE (POINT_SIZE * 3)

/**
 * Elements per output in field representation
 */
#define ELEMENTS_PER_OUTPUT 6

/**
 * Single layer of a branch
 */
typedef struct FcmpBranchLayer {
    /**
     * Number of elements in this layer
     */
    uint32_t num_elements;
    /**
     * Pointer to elements (array of 32-byte scalars)
     */
    const uint8_t *elements;
} FcmpBranchLayer;

/**
 * Branch data for proof generation
 */
typedef struct FcmpBranch {
    /**
     * Leaf index in the tree
     */
    uint64_t leaf_index;
    /**
     * Number of layers
     */
    uint32_t num_layers;
    /**
     * Pointer to layer data (array of FcmpBranchLayer)
     */
    const struct FcmpBranchLayer *layers;
} FcmpBranch;

/**
 * Input tuple for verification
 */
typedef struct FcmpInput {
    /**
     * Re-randomized O point (x, y coordinates as scalars)
     */
    uint8_t o_tilde[64];
    /**
     * Re-randomized I point
     */
    uint8_t i_tilde[64];
    /**
     * R value for SA+L
     */
    uint8_t r[64];
    /**
     * Re-randomized C point
     */
    uint8_t c_tilde[64];
} FcmpInput;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Initialize the FCMP library with default parameters.
 *
 * Must be called before any other FCMP functions.
 * Thread-safe for multiple calls (idempotent).
 *
 * # Returns
 * - `FCMP_SUCCESS` on success
 * - `FCMP_ERROR_*` on failure
 */
int32_t fcmp_init(void);

/**
 * Clean up and free FCMP resources.
 *
 * After calling this, `fcmp_init()` must be called again before using other functions.
 */
void fcmp_cleanup(void);

/**
 * Check if FCMP is initialized.
 *
 * # Returns
 * - 1 if initialized
 * - 0 if not initialized
 */
int32_t fcmp_is_initialized(void);

/**
 * Generate a random scalar.
 *
 * # Safety
 * - `out` must point to at least 32 bytes of writable memory
 */
int32_t fcmp_scalar_random(uint8_t *out);

/**
 * Add two scalars: out = a + b (mod l)
 *
 * # Safety
 * - All pointers must point to at least 32 bytes
 * - `out` must be writable
 */
int32_t fcmp_scalar_add(uint8_t *out, const uint8_t *a, const uint8_t *b);

/**
 * Multiply two scalars: out = a * b (mod l)
 *
 * # Safety
 * - All pointers must point to at least 32 bytes
 * - `out` must be writable
 */
int32_t fcmp_scalar_mul(uint8_t *out, const uint8_t *a, const uint8_t *b);

/**
 * Multiply a point by a scalar: out = scalar * point
 *
 * # Safety
 * - All pointers must point to at least 32 bytes
 * - `out` must be writable
 */
int32_t fcmp_point_mul(uint8_t *out, const uint8_t *scalar, const uint8_t *point);

/**
 * Add two points: out = a + b
 *
 * # Safety
 * - All pointers must point to at least 32 bytes
 * - `out` must be writable
 */
int32_t fcmp_point_add(uint8_t *out, const uint8_t *a, const uint8_t *b);

/**
 * Get the Ed25519 base point (generator)
 *
 * # Safety
 * - `out` must point to at least 32 bytes of writable memory
 */
int32_t fcmp_point_basepoint(uint8_t *out);

/**
 * Check if a point is valid (on the curve)
 *
 * # Safety
 * - `point` must point to at least 32 bytes
 *
 * # Returns
 * - 1 if valid
 * - 0 if invalid
 */
int32_t fcmp_point_is_valid(const uint8_t *point);

/**
 * Hash data to a scalar using BLAKE2b
 *
 * # Safety
 * - `out` must point to at least 32 bytes of writable memory
 * - `data` must point to `data_len` bytes
 */
int32_t fcmp_hash_to_scalar(uint8_t *out, const uint8_t *data, uintptr_t data_len);

/**
 * Hash data to a point using BLAKE2b + Elligator-like mapping
 *
 * # Safety
 * - `out` must point to at least 32 bytes of writable memory
 * - `data` must point to `data_len` bytes
 */
int32_t fcmp_hash_to_point(uint8_t *out, const uint8_t *data, uintptr_t data_len);

/**
 * Create a Pedersen commitment: C = value * G + blinding * H
 *
 * # Safety
 * - `out` must point to at least 32 bytes of writable memory
 * - `value` and `blinding` must each point to 32 bytes
 */
int32_t fcmp_pedersen_commit(uint8_t *out, const uint8_t *value, const uint8_t *blinding);

/**
 * Return the exact FCMP++ proof size for the given parameters.
 *
 * Uses the real `FcmpPlusPlus::proof_size` calculation.
 *
 * # Returns
 * - Exact proof size in bytes, or 0 if either argument is zero
 */
uintptr_t fcmp_proof_size(uint32_t num_inputs, uint32_t num_layers);

/**
 * Generate an FCMP proof (Schnorr sigma protocol on curve tree branch)
 *
 * # Safety
 * - All pointers must be valid
 * - `proof_out` must have at least `proof_max_len` bytes available
 * - `proof_len_out` must be writable
 *
 * # Proof structure:
 * - challenge `c` (32 bytes)
 * - For each tree layer: response `s_i` (32 bytes) + commitment `R_i` (32 bytes)
 * - Total size: 32 + num_layers * 64 bytes
 *
 * # Returns
 * - `FCMP_SUCCESS` on success
 * - Error code on failure
 */
int32_t fcmp_prove(uint8_t *proof_out,
                   uintptr_t *proof_len_out,
                   uintptr_t proof_max_len,
                   const uint8_t *tree_root,
                   const uint8_t *output,
                   const struct FcmpBranch *branch,
                   const uint8_t *secret_key,
                   const uint8_t *rerandomizer);

/**
 * Verify an FCMP proof (Schnorr sigma protocol verification)
 *
 * Proof format: c (32) || [s_0 (32) || R_0 (32)] || [s_1 (32) || R_1 (32)] || ...
 * For each layer i: verify s_i * G == R_i + c * layer_commitment_i
 * Then recompute Fiat-Shamir challenge and verify c == c'
 *
 * # Safety
 * - All pointers must be valid
 *
 * # Returns
 * - `FCMP_SUCCESS` if proof is valid
 * - `FCMP_ERROR_PROOF_VERIFICATION` if proof is invalid
 * - Other error codes on failure
 */
int32_t fcmp_verify(const uint8_t *tree_root,
                    const struct FcmpInput *input,
                    const uint8_t *proof,
                    uintptr_t proof_len);

/**
 * Generate a real FCMP++ membership proof for a leaf-level tree (1 layer: leaves → root).
 *
 * The caller provides all outputs in the leaf branch (`leaves_data`, `num_leaves` × 96 bytes,
 * each output encoded as O‖I‖C where each point is 32-byte compressed Ed25519), the index of
 * the output being spent (`our_leaf_index`), the spending key components `x` and `y` satisfying
 * `O = x·G + y·T`, and the 32-byte `signable_tx_hash`.
 *
 * On success the serialised `FcmpPlusPlus` proof is written to `proof_out`, its length to
 * `*proof_len_out`, the key image `L = x·I` to `key_image_out`, the pseudo-out `C~` to
 * `c_tilde_out`, and the commitment re-randomiser `r_c` to `c_blind_out`.  All three 32-byte
 * output buffers must be provided by the caller.
 *
 * `r_c` is required by the caller, not merely informative: the re-randomisation is
 * `C~ = C + r_c·G`, so the blinding of the pseudo-out is `b~ = b + r_c`, and a spender cannot
 * balance a transaction's output blindings against its inputs without it.  The blinds are drawn
 * inside `RerandomizedOutput::new` from the OS RNG, so this is the only way out.  Treat it as
 * secret: publishing `r_c` alongside `C~` would re-link the input to its tree leaf.
 *
 * # Safety
 * All pointers must be valid for the described lengths.
 */
int32_t fcmp_prove_full(uint8_t *proof_out,
                        uintptr_t *proof_len_out,
                        uintptr_t proof_max_len,
                        const uint8_t *leaves_data,
                        uintptr_t num_leaves,
                        uintptr_t our_leaf_index,
                        const uint8_t *x_bytes,
                        const uint8_t *y_bytes,
                        const uint8_t *tx_hash,
                        uint8_t *key_image_out,
                        uint8_t *c_tilde_out,
                        uint8_t *c_blind_out);

/**
 * Verify a real FCMP++ membership proof produced by `fcmp_prove_full`.
 *
 * `tree_root` is the 32-byte compressed Selene (C1) root point (for a 1-layer tree where
 * `num_layers` is odd, i.e. 1).  `pseudo_out` is the C~ value returned in `c_tilde_out` by
 * `fcmp_prove_full`.  `tx_hash` must be identical to the one used during proving.
 *
 * # Returns
 * - `FCMP_SUCCESS` if the proof verifies
 * - `FCMP_ERROR_PROOF_VERIFICATION` if it does not
 * - Other error codes on bad inputs
 *
 * # Safety
 * All pointers must be valid for 32 bytes each.
 */
int32_t fcmp_verify_full(const uint8_t *tree_root,
                         uintptr_t num_layers,
                         const uint8_t *proof_data,
                         uintptr_t proof_len,
                         const uint8_t *key_image,
                         const uint8_t *pseudo_out,
                         const uint8_t *tx_hash);

/**
 * Compute the Selene (C1) tree root from a leaf branch for a 1-layer tree.
 *
 * `leaves_data` points to `num_leaves` × 96 bytes (O‖I‖C for each output, each 32-byte
 * compressed Ed25519).  The computed Selene root is written as 32 compressed bytes to
 * `root_out`.
 *
 * This mirrors the root computation inside `Fcmp::prove` for a single leaf branch, and must
 * be used to obtain the `tree_root` value passed to `fcmp_verify_full`.
 *
 * # Safety
 * All pointers must be valid for the described lengths.
 */
int32_t fcmp_compute_leaf_root(uint8_t *root_out, const uint8_t *leaves_data, uintptr_t num_leaves);

/**
 * Get the library version string
 *
 * # Returns
 * Pointer to a null-terminated version string
 */
const int8_t *fcmp_version(void);

/**
 * Get error message for an error code
 *
 * # Returns
 * Pointer to a null-terminated error string
 */
const int8_t *fcmp_error_string(int32_t code);

/**
 * Hash one layer of Selene points into their Helios parent.
 *
 * `children` is `num_children` × 32 bytes, each a compressed Selene point.
 * `root_out` receives a 32-byte compressed Helios point.
 */
int32_t fcmp_hash_helios_layer(uint8_t *root_out, const uint8_t *children, uintptr_t num_children);

/**
 * Hash one layer of Helios points into their Selene parent.
 *
 * `children` is `num_children` × 32 bytes, each a compressed Helios point.
 * `root_out` receives a 32-byte compressed Selene point.
 */
int32_t fcmp_hash_selene_layer(uint8_t *root_out, const uint8_t *children, uintptr_t num_children);

/**
 * Branch widths, so the C++ tree does not hard-code constants that live here.
 */
uintptr_t fcmp_layer_one_len(void);

uintptr_t fcmp_layer_two_len(void);

#ifdef __cplusplus
} // extern "C"
#endif // __cplusplus

#endif /* WATTX_FCMP_FFI_H */
